version: "3.9"
name: spring-boot-loki
### SERVICES ###
services:
  springbootapp:
    container_name: springbootapp-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10100:8080"
    environment:
      - TZ
      - JSON_LOGS_ENABLED=true
      - JAVA_OPTS=-Dspring.profiles.active=docker -javaagent:opentelemetry-javaagent.jar
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_TRACES_SAMPLER=always_on
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://grafana-tempo:4318/v1/traces
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_SERVICE_NAME=spring-boot-app-1
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: postgres-1
    image: postgres:latest
    ports:
      - "10001:5432"
    volumes:
      - ./docker/postgres/init-ddl.sql:/docker-entrypoint-initdb.d/init-ddl.sql
      - postgres:/var/lib/postgresql/data
    environment:
      - TZ
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
  grafana:
    container_name: grafana-1
    image: grafana/grafana:latest
    links:
      - grafana-loki
      - prometheus
    ports:
      - "10000:3000"
    volumes:
      - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - TZ
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  grafana-loki:
    container_name: grafana-loki-1
    image: grafana/loki:latest
    ports:
      - "10003:3100"
    environment:
      - TZ
  grafana-tempo:
    container_name: grafana-tempo-1
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yaml:/etc/tempo.yaml
      ###- grafana-tempo:/tmp/tempo
      - ./tempo-data:/tmp/tempo
    #    ports:
    #      - "3200:3200"  # tempo
    #      - "4317:4317"  # otlp grpc
    #      - "4318:4318"  # otlp http
    environment:
      - TZ
  prometheus:
    container_name: prometheus-1
    image: prom/prometheus:latest
    ports:
      - "10002:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    environment:
      - TZ
### VOLUMES ###
volumes:
  prometheus:
  postgres:
  #grafana-tempo:
