version: "3.9"
name: spring-boot-loki
### SERVICES ###
services:
  grafana:
    image: grafana/grafana:latest
  grafana-loki:
    image: grafana/loki:latest
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus:/prometheus
### VOLUMES ###
volumes:
  prometheus:
