apiVersion: 1
datasources:
  - name: Loki-1
    type: loki
    access: proxy
    orgId: 1
    url: http://grafana-loki-1:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: true