apiVersion: 1
datasources:
  - name: Prometheus-1
    type: prometheus
    uid: PF8CB2B50324B125B
    access: proxy
    orgId: 1
    url: http://prometheus-1:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: true