apiVersion: 1
datasources:
  - name: Prometheus-1
    type: prometheus
    access: proxy
    orgId: 1
    url: http://grafana-prometheus-1:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: true